import { TextWeight } from './typography-types.ts';

// Mapping weight number to font family name
export const weightToFontFamily: Record<TextWeight, string> = {
  300: 'Roboto-Light',
  400: 'Roboto-Regular',
  500: 'Roboto-Medium',
  600: 'Roboto-SemiBold',
  700: 'Roboto-Bold',
  900: 'Roboto-Black',
};

export const IconEnum = {
  Back: '󰀀',
  BangStar: '󰀁',
  Check: '󰀂',
  ChevronDown: '󰀃',
  ChevronLeft: '󰀄',
  ChevronRight: '󰀅',
  ChevronUp: '󰀆',
  Close: '󰀇',
  Edit: '󰀈',
  Export: '󰀉',
  Import: '󰀊',
  Refresh: '󰀋',
  Save: '󰀌',
  Star: '󰀍',
  Tasks: '󰀎',
  Trash: '󰀏',
  BasketballFill: '󰀐',
  BeerFill: '󰀑',
  CalendarFill: '󰀒',
  ColorFill: '󰀓',
  DumbFill: '󰀔',
  HockeyFill: '󰀕',
  ImageFill: '󰀖',
  KabaddiFill: '󰀗',
  LowKickFill: '󰀘',
  MedalFill: '󰀙',
  MotorshipFill: '󰀚',
  ProgressFill: '󰀛',
  SettingsFill: '󰀜',
  SoccerFill: '󰀝',
  SportsFill: '󰀞',
  StarFill: '󰀟',
  SwimFill: '󰀠',
  TasksFill: '󰀡',
  TimeFill: '󰀢',
  UserFill: '󰀣',
  VideoFill: '󰀤',
  VolleyballFill: '󰀥',
} as const;
export type IconEnum = (typeof IconEnum)[keyof typeof IconEnum];
